@startuml

skinparam componentStyle uml2

component [CargoBookingContext]
component [VoyagePlanningContext]
component [LocationContext]

[CargoBookingContext]<-->[VoyagePlanningContext] : Shared Kernel

interface "Upstream-Downstream" as CargoBookingContext_to_LocationContext
[LocationContext] --> CargoBookingContext_to_LocationContext
CargoBookingContext_to_LocationContext <.. [CargoBookingContext] : consume

interface "Upstream-Downstream" as VoyagePlanningContext_to_LocationContext
[LocationContext] --> VoyagePlanningContext_to_LocationContext
VoyagePlanningContext_to_LocationContext <.. [VoyagePlanningContext] : consume

@enduml